server:
  port: 8080

debug: false

logging:
  level:
    root: info
    org.mybatis: debug
    org.springframework: info
    org.springframework.jdbc: debug
    com.github.trang: debug
    com.lumi.aiot.cloud: debug

spring:
  profiles:
    configure:
      includes:
      - com.lumi.aiot.cloud.config.Swagger2Config
  datasource:
    url: jdbc:mysql://192.168.100.69:3306/iot-test
    username: root
    password: qwe123456
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 10
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      use-global-data-source-stat: true
      stat:
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: true
      slf4j:
        enabled: true
        data-source-log-enabled: true
        connection-log-enabled: false
        connection-log-error-enabled: true
        statement-log-enabled: false
        statement-log-error-enabled: true
        statement-sql-pretty-format: false
        statement-parameter-set-log-enabled: false
        statement-prepare-after-log-enabled: false
        statement-close-after-log-enabled: false
        statement-executable-sql-log-enable: true
        result-set-log-enabled: false
        result-set-log-error-enabled: true
      wall:
        enabled: true
        log-violation: true
        throw-exception: false
  cache:
    type: none
    data:
      　　mongodb:
        　　uri: mongodb://localhost:27017/boot_mongo

redis:
  database: 0
  host: localhost
  port: 6379
  password:
  timeout: 0
  pool:
    max-active: 8
    max-idle: 8
    min-idle: 0
    max-wait: -1
